name: Release

on:
  workflow_dispatch:


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: |
            npm install --package-lock-only
            npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Semantic Release
        run: |
            npx -p @semantic-release/commit-analyzer -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
